-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE
FROM
    (SELECT COM.CAR_ID, COM.CAR_TYPE
     , CAST(COM.DAILY_FEE * 30 * (100 - DIS.DISCOUNT_RATE) / 100 AS INTEGER) FEE
    FROM
        CAR_RENTAL_COMPANY_CAR COM, CAR_RENTAL_COMPANY_DISCOUNT_PLAN DIS
    WHERE (COM.CAR_TYPE = '세단' OR COM.CAR_TYPE = 'SUV') 
    AND COM.CAR_TYPE = DIS.CAR_TYPE AND DIS.DURATION_TYPE LIKE '30%'
    AND COM.CAR_ID NOT IN
        (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
            WHERE TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101' AND TO_CHAR(START_DATE, 'YYYYMMDD') < '20221201'
        )
    )
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;