-- 코드를 입력하세요
SELECT YEAR, MONTH, PUCHASED_USERS, ROUND(PUCHASED_USERS / TOTAL_USERS, 1) PUCHASED_PATIO
FROM (
    SELECT TO_CHAR(I2.SALES_DATE, 'YYYY') YEAR, TO_NUMBER(TO_CHAR(I2.SALES_DATE, 'MM')) MONTH
            , COUNT(DISTINCT I2.USER_ID) PUCHASED_USERS
    , (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021') TOTAL_USERS
    FROM USER_INFO I1 JOIN ONLINE_SALE I2 ON (I1.USER_ID = I2.USER_ID)
    WHERE TO_CHAR(I1.JOINED, 'YYYY') = '2021' 
    GROUP BY TO_CHAR(I2.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(I2.SALES_DATE, 'MM'))
) A
ORDER BY YEAR, MONTH