-- 코드를 작성해주세요
SELECT 
    YEAR(DIFFERENTIATION_DATE) YEAR, 
    (
        (SELECT MAX(SIZE_OF_COLONY) 
         FROM ECOLI_DATA I 
         WHERE YEAR(I.DIFFERENTIATION_DATE) = YEAR(O.DIFFERENTIATION_DATE))
        - SIZE_OF_COLONY) YEAR_DEV
    , ID
FROM ECOLI_DATA O
ORDER BY YEAR, YEAR_DEV