-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 DEPTH FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, B.DEPTH + 1 DEPTH
    FROM ECOLI_DATA E JOIN CTE B ON (E.PARENT_ID = B.ID)
)
SELECT ID FROM CTE WHERE DEPTH = 3 ORDER BY ID;