-- 코드를 작성해주세요
SELECT A.ID, CASE
    WHEN A.RANKING / B.TOTAL <= 0.25 THEN 'CRITICAL'
    WHEN A.RANKING / B.TOTAL <= 0.5 THEN 'HIGH'
    WHEN A.RANKING / B.TOTAL <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM
(SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) RANKING FROM ECOLI_DATA) A, 
(SELECT COUNT(ID) TOTAL FROM ECOLI_DATA) B
ORDER BY ID;