-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD')
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID)
WHERE M.MEMBER_ID IN (
    SELECT MI.MEMBER_ID
    FROM MEMBER_PROFILE MI JOIN REST_REVIEW RI ON (MI.MEMBER_ID = RI.MEMBER_ID)
    GROUP BY MI.MEMBER_ID HAVING COUNT(*) = (
        SELECT C FROM (
            SELECT
                COUNT(*) C
            FROM
                MEMBER_PROFILE MII JOIN REST_REVIEW RII ON (MII.MEMBER_ID = RII.MEMBER_ID)
            GROUP BY MII.MEMBER_ID
            ORDER BY C DESC
        ) WHERE ROWNUM = 1
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;