-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, TO_CHAR(ROUND(AVG(REVIEW_SCORE), 2), 'FM0.00') SCORE
FROM REST_INFO I JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY AVG(REVIEW_SCORE) DESC NULLS LAST, FAVORITES DESC;