-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S JOIN BOOK B ON(B.BOOK_ID = S.BOOK_ID)
WHERE EXTRACT(YEAR FROM CAST(S.SALES_DATE AS DATE)) = 2022 AND EXTRACT(MONTH FROM CAST(S.SALES_DATE AS DATE)) = 1
GROUP BY B.CATEGORY 
ORDER BY B.CATEGORY;
