-- 코드를 작성해주세요
SELECT ID, GENOTYPE, (SELECT P.GENOTYPE FROM ECOLI_DATA P WHERE C.PARENT_ID = P.ID) PARENT_GENOTYPE FROM
ECOLI_DATA C
WHERE (C.GENOTYPE |
(SELECT P.GENOTYPE FROM ECOLI_DATA P WHERE C.PARENT_ID = P.ID) = C.GENOTYPE);