-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES FROM BOOK_SALES BS JOIN BOOK B ON(BS.BOOK_ID = B.BOOK_ID) JOIN AUTHOR A ON(A.AUTHOR_ID = B.AUTHOR_ID)
WHERE SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD') AND SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY A.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;