-- 코드를 입력하세요

SELECT DISTINCT H.HISTORY_ID
, 
C.DAILY_FEE * (END_DATE - START_DATE + 1)
* (100 - NVL((SELECT 
          MAX(DISCOUNT_RATE) 
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
   WHERE SUBSTR(LPAD(DURATION_TYPE, 7, '0'), 1, 2) <= H.END_DATE - H.START_DATE
             AND CAR_TYPE = C.CAR_TYPE AND CAR_TYPE = '트럭'
             ), 0)) / 100 FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P, CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR C
WHERE P.CAR_TYPE = C.CAR_TYPE AND C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
-- GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC