-- 코드를 작성해주세요
SELECT SUM(G.SCORE) SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
FROM HR_GRADE G, HR_EMPLOYEES E, HR_DEPARTMENT D
WHERE G.EMP_NO = E.EMP_NO AND E.DEPT_ID = D.DEPT_ID GROUP BY G.EMP_NO
ORDER BY SCORE DESC LIMIT 1;