-- 코드를 입력하세요
SELECT A.FLAVOR FROM
(SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) TOTAL
FROM FIRST_HALF F
    JOIN JULY J ON (F.FLAVOR = J.FLAVOR) 
    GROUP BY (F.FLAVOR)
    ORDER BY TOTAL DESC LIMIT 3) A;