-- 코드를 작성해주세요
SELECT ID, FISH_NAME, A.LENGTH
FROM
(SELECT FISH_TYPE, MAX(LENGTH) LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) A 
JOIN FISH_INFO B ON (A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH) 
JOIN FISH_NAME_INFO C ON (B.FISH_TYPE = C.FISH_TYPE) 
ORDER BY ID;