-- 코드를 입력하세요
SELECT MCDP_CD AS "진료과코드", COUNT(*) AS "5월예약건수"
FROM APPOINTMENT 
    WHERE EXTRACT(YEAR FROM CAST(APNT_YMD AS DATE)) = 2022 
    AND EXTRACT(MONTH FROM CAST(APNT_YMD AS DATE)) = 5
GROUP BY MCDP_CD
ORDER BY "5월예약건수", "진료과코드";